### PR TITLE
Remove ref to multi example (v2.03)

### LINKED ISSUE #433: Remove remaining reference to activity-standard-example-annotated-multi.xml
At the bottom of the [Example Usage XML](http://iatistandard.org/202/activity-standard/example-xml/) page, it says:

> _Example usage XML_ - with multiple values:
>
> [nothing]
>
> ## Further guidance
> […]

That’s because this is the one remaining reference to activity-standard-example-annotated-multi.xml:
https://github.com/IATI/IATI-Extra-Documentation/blob/d282e11/en/activity-standard/example-xml.rst#L37

This file no longer exists at v2.0x (presumably because it’s not terribly different from the non-multi version) but in any case it would be good to remove this final reference.

### PR DESCRIPTION
**Pull request by andylolz**
Fixes #433.

NB this should be fixed on other branches, too.

### CODE REVIEW

**Review by dalepotter — APPROVED** [review]

**Comment by dalepotter** [comment]
Happy with this and thanks @andylolz 

As with other PRs, this fix should also be applied to the `version-1.04`, `version-1.05`, `version-2.01` and `version-2.02` branches. I'd suggest they are all merged at once (within a few minutes) to avoid inconsistencies between versions (even for this level of change).

**Comment by andylolz** [comment]
> As with other PRs, this fix should also be applied to the `version-1.04`, `version-1.05` […]

I’ve sent the PRs for `version-2.01` and `version-2.02`, but not really sure what to do about v1.0x.

For v1.0x, activity-standard-example-annotated-multi.xml is present, and is used in lots of examples. It looks like the file was removed in v2.0x because it doesn’t really add much. References to it were mostly removed, but this one remains.

**Comment by dalepotter** [comment]
> For v1.0x, activity-standard-example-annotated-multi.xml is present, and is used in lots of examples. It looks like the file was removed in v2.0x because it doesn’t really add much. References to it were mostly removed, but this one remains.

Thanks for looking into that - let's leave things be for `v1.xx`.

**Comment by dalepotter** [comment]
A note that PRs for other branches are here:
- `version-2.01` #448
- `version-2.02` #447

**Review by dalepotter — APPROVED** [review]

**Pull request merged**
