### PR TITLE
Add doc links in results 359

### PR DESCRIPTION
**Pull request by amy-silcock**
Add Extra Documentation as per: https://github.com/IATI/IATI-Schemas/issues/359

### CODE REVIEW

**Comment by amy-silcock** [comment]
@IATI/devs Can you please have a look to see why 2 checks are failing?

**Comment by hayfield** [comment]
I've set Travis running against the intermediate commits that were previously untested. This should identify in which commit the problem was introduced.

**Comment by hayfield** [comment]
The tests have now run, showing that the problem is in https://github.com/IATI/IATI-Extra-Documentation/pull/391/commits/99224c20ad16e80a63aa2c468691ffe18c32e365

**Comment by hayfield** [comment]
The issue seems to be that the Schema is expecting that `document-link` and `comment` are the other way round:

* https://github.com/IATI/IATI-Schemas/blob/version-2.03dev/iati-activities-schema.xsd#L1639-L1640
* https://github.com/IATI/IATI-Schemas/blob/version-2.03dev/iati-activities-schema.xsd#L1664-L1665

**Review by PetyaKangalova — APPROVED** [review]

**Comment by dalepotter** [comment]
Includes some `:emphasize-lines`, but would suggest #413 is re-run in order to remove these en masse after this and other PRs are merged into v2.03 dev.

**Pull request merged**
