### PR TITLE
Clarify wording on country and region budgets 2.01

### PR DESCRIPTION
**Pull request by amy-silcock**
https://github.com/IATI/IATI-Extra-Documentation/issues/351

### CODE REVIEW

**Comment by rolfkleef** [comment]
There is an edge case here: it is possible to use different region vocabularies.

I would say that for each region vocabulary used, the sum of percentages for countries plus regions in that vocabulary should be 100.

```
<recipient-country code=... percentage="50">
# Region according to OECD DAC:
<recipient-region vocabulary="1" code=... percentage="50">
# Region according to our own division:
<recipient-region vocabulary="99" code=... percentage="50">
```

Or, with just regions when you want to use for instance your own regions based on partner networks but have to publish DAC regions too:

```
# Regions according to OECD DAC:
<recipient-region vocabulary="1" code="619" percentage="50">
<recipient-region vocabulary="1" code="679" percentage="50">
# Regions according to our own division:
<recipient-region vocabulary="99" code="Network-1" percentage="25">
<recipient-region vocabulary="99" code="Network-2" percentage="75">
```

**Comment by rolfkleef** [comment]
There is an edge case here: it is possible to use different region vocabularies.

I would say that for each region vocabulary used, the sum of percentages for countries plus regions in that vocabulary should be 100.

```
<recipient-country code=... percentage="50">
# Region according to OECD DAC:
<recipient-region vocabulary="1" code=... percentage="50">
# Region according to our own division:
<recipient-region vocabulary="99" code=... percentage="50">
```

Or, with just regions when you want to use for instance your own regions based on partner networks but have to publish DAC regions too:

```
# Regions according to OECD DAC:
<recipient-region vocabulary="1" code="619" percentage="50">
<recipient-region vocabulary="1" code="679" percentage="50">
# Regions according to our own division:
<recipient-region vocabulary="99" code="Network-1" percentage="25">
<recipient-region vocabulary="99" code="Network-2" percentage="75">
```

**Comment by amylsilcock** [comment]
Hi @rolfkleef, we can change the wording to make it clearer that multiple regions can be given.

However, the wording in the IATI Standard doesn't distinguish between OECD DAC, UN and self reported vocabs. The rules is that the sum of all recipient-regions + recipient-countries must add up to 100% (regardless of vocabularies).

So your two examples above are incorrect, as they equal 150% and 200%. Unless I am mistaken?

**Comment by amy-silcock** [comment]
Hi @rolfkleef, we can change the wording to make it clearer that multiple regions can be given.

However, the wording in the IATI Standard doesn't distinguish between OECD DAC, UN and self reported vocabs. The rules is that the sum of all recipient-regions + recipient-countries must add up to 100% (regardless of vocabularies).

So your two examples above are incorrect, as they equal 150% and 200%. Unless I am mistaken?

**Comment by andylolz** [comment]
This isn’t especially clear in the docs currently, but I think @rolfkleef is right.

Elsewhere in the standard, I _thought_ vocabularies were treated as independent, and we shouldn’t sum across them. However, while [the example in the sector docs suggests this](http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/sector/#example-usage), the text itself doesn’t.

```xml
  <sector vocabulary="2" code="111" percentage="50" />
  <sector vocabulary="2" code="112" percentage="50" />
  <sector vocabulary="98" vocabulary-uri="http://example.com/vocab.html" code="A1" percentage="100" />
```

I suggest discussing with @PetyaKangalova, as [one of her discuss threads from last year](https://discuss.iatistandard.org/t/allow-multiple-vocabularies-recipient-region/1105) is relevant. Although it’s about a different element, it does suggest that `recipient-region`s from different vocabularies should be treated as independent.

Also, this line from the docs suggests the same:

> Please note, if using your own vocabulary (i.e. code 99), it is recommended that this is used in addition to the DAC OECD region vocabulary (code 1).

This would be a weird recommendation unless the values from different vocabularies should be treated as independent.

**Comment by rolfkleef** [comment]
I would say that conceptually it does make sense to have for instance two independent region lists. An organisation we work for has its own regions based on networks of partner organisations they work with, and may want to use this for their own visualisations. But they also should report according to the DAC regions to fulfil the needs of their donor. These are independent divisions.

@andylolz  For [sectors](http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/sector/) it does say for `@percentage`: "All reported sectors __from the same vocabulary__ MUST add up to 100."

I'd be open for a data use scenario where it makes sense to "pick and choose" from various vocabularies, since that makes most aggregation virtually impossible.

**Comment by andylolz** [comment]
> An organisation we work for has its own regions based on networks of partner organisations they work with, and may want to use this for their own visualisations. But they also should report according to the DAC regions to fulfil the needs of their donor. These are independent divisions.

Agreed – I think that’s consistent with the example @PetyaKangalova provided on [the discuss post](https://discuss.iatistandard.org/t/allow-multiple-vocabularies-recipient-region/1105?u=andylolz) linked above.

> @andylolz For [sectors](http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/sector/) it does say for `@percentage`: "All reported sectors from the same vocabulary MUST add up to 100."

Oh yes – good point, you’re right. But the same page also says:

> When multiple `sector` are declared, then the `@percentage` values should sum to 100% for the specific `iati-activity`.

(I.e. no mention of vocabularies in this text). Similarly, the [relevant ruleset rule](https://github.com/IATI/IATI-Rulesets/blob/e77e6860ceba3be71d95c7ed95b9c78f3f29928e/rulesets/standard.json#L24-L27) makes no mention of vocabularies, suggesting they shouldn’t be treated as independent. But these ruleset rules should probably include a disclaimer, because they are so rarely correct.

So what I mean is: I think you’re right @rolfkleef, and I think the documentation probably needs to be updated in various places to reflect that consistently.

**Comment by amy-silcock** [comment]
This changes following this discussion have now been approved: https://discuss.iatistandard.org/t/approved-rules-for-reporting-multiple-countries-and-regions-proposed-bug-fix/1719/2 

The PR to make the changes in v2.01 in the documentation has happened here: https://github.com/IATI/IATI-Extra-Documentation/pull/559

Thank you all for your contributions

**Pull request closed without merging**
