### PR TITLE
Fixes link formatting on codelist changelog

### PR DESCRIPTION
**Pull request by stevieflow**

### CODE REVIEW

**Comment by Bjwebb** [comment]
If you must use absolute URLs, it would be better to use ones that don't currently 404 (especially since 2.01 is likely to be on the dev site until December/January).

It would be better to use `:ref:` though http://sphinx-doc.org/markup/inline.html#role-ref

**Comment by stevieflow** [comment]
ok - try it now - changed to :ref:

**Comment by Bjwebb** [comment]
You need to do more than just replace `:doc:` with `:ref:`.

You need to add a named label above the relevant section, like https://github.com/IATI/IATI-Extra-Documentation/blame/version-1.04/en/codelists/codelist-api.rst#L27
and then ref that - see "Download this codelist" section in http://iatistandard.org/_sources/codelists/ActivityDateType.txt

**Comment by stevieflow** [comment]
OK - pushing this ticket into 2.01 release - to be fixed in the next week or so

**Comment by stevieflow** [comment]
Sorry - I'm still not really following this

Can you tell me from https://github.com/IATI/IATI-Extra-Documentation/blob/6d38a494a18c19421b19694deb352c5925c00ad0/en/codelists/%20CRSAddOtherFlags.rst

what I need to add/edit/delete:

`The *AidTypeFlag* was :ref:`renamed <upgrades/integer-upgrade-to-2-01/2-01-changes.html#aid-type-flag-renamed-codelist>`  to *CRSAddOtherFlags*`

**Comment by stevieflow** [comment]
@Bjwebb does this need to remain open?

**Comment by Bjwebb** [comment]
No, I think this can be closed now, as you seem to have resolved the underlying issue using absolute URLs instead - http://dev.iatistandard.org/201/codelists/Version/

**Pull request closed without merging**
